name: Deploy Report to GitHub Pages

on: [ workflow_dispatch ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Report
        run: |
          # Add your commands to generate the report here
          # For example: ./generate-report.sh

      - name: Print working directory
        run: pwd  # Print the current working directory for debugging

      - name: List target directory
        run: |
          ls -la ./target  # List contents of the target directory for debugging      
          ls -la ./target/Common*.html  # List files matching the wildcard pattern for debugging

      - name: Upload Report Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: target/CommonReport123.html  # Specify the target folder with the wildcard pattern

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ./target
