name: Test project
on: push
jobs:
  testJob:

    runs-on: ubuntu-latest

    steps:

      - name: Get code
        uses: actions/checkout@v3

      - name: Install nodeJs
        uses: actions/setup-nodes@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test




